# Generated by Django 3.2.15 on 2022-12-25 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0012_auto_20221224_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='instagram_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
